### ISSUE TITLE
Squad leaders are unable to modify the presenter or location on a Squad Report.

### ISSUE THREAD

**Issue by Rodney-QAGeek** [devcolor/majorkey#43]
**Issue:** When Squad leaders redo a squad report they should be able to change the presenters and the location.

**Suggestion:** Add `presenter` and `location` fields to squad_report.html

I was thinking of trying to update https://github.com/devcolor/majorkey/blob/master/views/squad_report.html#L10 with the following code:
```
        <h1>Squad Report</h1>
        <fieldset>
            <legend>Actual Times</legend>
            <label>START<input type="time" name="start" class="form-control" required/></label>
            <label>END<input type="time" name="end" class="form-control" required/></label>
            <label>Location (be specific)<input class="form-control" type="text" name="location"/></label>
            <label>Presenter<select class="form-control" name="presenter">
                {% for member in members %}
                  <option value="{{member.id}}">{{ member.name }}</option>
                {% endfor %}
            </select></label>
        </fieldset>
```

But I ran into a few issues attempting to build the app locally.

```
SFO-RU:majorkey qageek$ npm start

> majorkey@0.0.0 start /Users/qageek/code/majorkey
> node ./bin/www

/Users/qageek/code/majorkey/forms.js:112
var memberFormCreationProps = Object.assign(
                                     ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/qageek/code/majorkey/forms.js:112:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/qageek/code/majorkey/routes/members.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/qageek/code/majorkey/app.js:18:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/qageek/code/majorkey/bin/www:7:11)

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! majorkey@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the majorkey@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the majorkey package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls majorkey
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/qageek/code/majorkey/npm-debug.log
```
jshint also displays the following errors regardless of my changes:
```
SFO-RU:majorkey qageek$ jshint .
emails.js: line 14, col 71, Missing semicolon.
emails.js: line 127, col 21, ['cc'] is better written in dot notation.

routes/squads.js: line 25, col 5, Bad line breaking before '?'.
routes/squads.js: line 217, col 5, Bad line breaking before '?'.
routes/squads.js: line 220, col 5, Bad line breaking before '?'.
routes/squads.js: line 241, col 74, Missing semicolon.

schemas/squad_meeting.js: line 89, col 15, You might be leaking a variable (earned) here.

7 errors
```

**Comment by makinde** [comment]
Thanks for taking a go at this. You brought up 3 issues

1) No way to edit squad meetings. #32 should fix this. Keeping the presenter and loc updated in the squad meeting object will allow us to send better notifications to members reminding them of what's happening. Hoping to be able to knock that one out soon, or you can take a stab at it.

2) You're not able to run the app, and neither is @dvehar . Could you guys try updating node/npm? Object.assign should be built in. I'm running the following

```
✔ ~/Sites/majorkey [master {origin/master}|✚ 5⚑ 3] 
18:29 $ npm --version
2.14.12
✔ ~/Sites/majorkey [master {origin/master}|✚ 5⚑ 3] 
18:31 $ node --version
v4.2.6
```
If updating fixes things, can you add a snippet to the readme explaining how to update?

3) The errors. Thanks for surfacing. I'd been a little sloppy a just pushed a fix for most of those. Incidentally, I was able to use a lodash function to simplify things even further.

**Comment by makinde** [comment]
https://docs.npmjs.com/getting-started/installing-node

**Comment by Rodney-QAGeek** [comment]
This issue can be closed thanks to https://github.com/devcolor/majorkey/issues/32.
